spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_library?useSSL=false&characterEncoding=utf-8
    username: root
    password: "000411"
#  redis:
#    host: 127.0.0.1
#    port: 6379
jedis:
  host: 127.0.0.1
  port: 6379